# Generated by Django 5.2.9 on 2025-12-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfiles', '0002_customuser_farm_location_savedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedfile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
